### ISSUE TITLE
Top of the game is up too far

### ISSUE THREAD

**Issue by gbxl** [ivailop7/IvoTetris#1]
Using Firefox, the top of the game is pushed all the way up, so far that a good 20% of the screen is hidden. I think the `box-three` class and it's -450px top margin are to blame!

**Comment by ivailop7** [comment]
Hey! Thanks for taking the time to enter this. I did fixed dimensions back then, as I never expected it to gain popularity. Will have a look at fixing these annoyances later this year.
Best regards, Ivo

**Comment by ivailop7** [comment]
Thanks for mentioning this one. It was an easy one to fix. Updated the code. Should be rendering correctly now. Will redeploy it in the coming days.
